"apiVersion": "argoproj.io/v1alpha1"
"kind": "Application"
"metadata":
  "name": "cert-manager"
  "namespace": "argocd"
"spec":
  "destination":
    "namespace": "cert-manager"
    "server": "https://kubernetes.default.svc"
  "project": "default"
  "source":
    "chart": "cert-manager"
    "helm":
      "parameters":
      - "name": "installCRDs"
        "value": "true"
      - "name": "ingressShim.defaultIssuerName"
        "value": "letsencrypt-prod"
      - "name": "ingressShim.defaultIssuerKind"
        "value": "ClusterIssuer"
      - "name": "ingressShim.defaultIssuerGroup"
        "value": "cert-manager.io"
      - "name": "rbac.serviceAccountAnnotations.eks\\.amazonaws\\.com/role-arn"
        "value": "arn:aws:iam::641456973426:role/swisskubehovo_cert-manager"
      - "name": "aws.region"
        "value": "eu-north-1"
      - "name": "domainFilters[0]"
        "value": "swisskubehovo.swiss.sak.agent"
    "repoURL": "https://charts.jetstack.io"
    "targetRevision": "v1.4.0"
  "syncPolicy":
    "automated":
      "prune": true
      "selfHeal": true
