"apiVersion": "cert-manager.io/v1alpha2"
"kind": "ClusterIssuer"
"metadata":
  "name": "letsencrypt-staging"
"spec":
  "acme":
    "email": "hkhalatyan@provectus.com"
    "privateKeySecretRef":
      "name": "letsencrypt-staging"
    "server": "https://acme-staging-v02.api.letsencrypt.org/directory"
    "solvers":
    - "dns01":
        "route53":
          "hostedZoneID": "Z04917561CQAI9UAF27D6"
          "region": "eu-north-1"
